# Generated by Django 4.2.7 on 2025-11-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_demoportfolio_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='flashcards_flipped',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='mcqs_progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
