# Generated by Django 5.2.8 on 2025-11-20 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('starting_balance', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('decision_type', models.CharField(choices=[('INVEST', 'Invest'), ('SAVE', 'Save'), ('SPEND', 'Spend')], max_length=10)),
                ('balance_impact', models.DecimalField(decimal_places=2, help_text='Negative for spending, positive for income', max_digits=10)),
                ('confidence_delta', models.IntegerField(default=0, help_text='e.g. +10 or -5')),
                ('risk_score_delta', models.IntegerField(default=0, help_text='0-100 scale impact')),
                ('future_growth_rate', models.DecimalField(decimal_places=4, default=0.0, help_text='Annual return rate (e.g. 0.12 for 12%)', max_digits=5)),
                ('why_it_matters', models.TextField(help_text='Educational context text')),
                ('mentor_feedback', models.CharField(help_text='Short snappy feedback', max_length=255)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='simulator.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='UserScenarioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_played', models.DateTimeField(auto_now_add=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
