# Generated by Django 4.2.7 on 2025-11-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscenariolog',
            options={'ordering': ['-date_played']},
        ),
        migrations.AlterField(
            model_name='userscenariolog',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator.scenario'),
        ),
    ]
