# Generated by Django 4.2.7 on 2025-11-21 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simulator', '0002_alter_userscenariolog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScenarioProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_scenario_id', models.IntegerField(blank=True, help_text='For JSON-based scenarios', null=True)),
                ('current_state', models.JSONField(blank=True, default=dict)),
                ('best_score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('times_played', models.IntegerField(default=0)),
                ('last_played', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='simulator.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scenario'], name='simulator_u_user_id_c3672b_idx')],
                'unique_together': {('user', 'scenario')},
            },
        ),
        migrations.CreateModel(
            name='UserScenarioCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_scenario_id', models.IntegerField(blank=True, help_text='For JSON-based scenarios', null=True)),
                ('custom_content', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_customizations', to='simulator.scenario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_customizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scenario'], name='simulator_u_user_id_920365_idx')],
                'unique_together': {('user', 'scenario')},
            },
        ),
    ]
