# Generated by Django 4.2.7 on 2025-11-21 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='version',
        ),
        migrations.RemoveField(
            model_name='mentorpersona',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mentorpersona',
            name='expertise_tags',
        ),
        migrations.RemoveField(
            model_name='mentorpersona',
            name='mentor_id',
        ),
        migrations.RemoveField(
            model_name='mentorpersona',
            name='role',
        ),
        migrations.RemoveField(
            model_name='mentorpersona',
            name='system_prompt',
        ),
        migrations.RemoveField(
            model_name='mentorpersona',
            name='tone_profile',
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorpersona',
            name='avatar_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mentorpersona',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_id',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='parent_topic',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_id',
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('module_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='json_course_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course_id'], name='courses_use_user_id_35c5b3_idx'), models.Index(fields=['user', 'course_id', 'module_id'], name='courses_use_user_id_ca503c_idx')],
                'unique_together': {('user', 'course_id', 'module_id')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=100)),
                ('custom_content', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_customizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course_id'], name='courses_use_user_id_536393_idx')],
                'unique_together': {('user', 'course_id')},
            },
        ),
    ]
